version: '3.8'

services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgres://avnadmin:AVNS_jOM3C-8F6-XCYUm__wi@pg-ee910fc-supersaiyan0754-4da4.i.aivencloud.com:18202/studentDB?sslmode=require
    ports:
      - "8080:8080"  # Expose port 8080 from the container to the host machine
